import Head from 'next/head'
import React from 'react'
import DashboardLayout from '../../../components/DashboardLayout'
import { Courses } from "../../../data"


const SingleAttendance = () => {

       console.log(Courses)
    return (
        <div>

            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <DashboardLayout>
                    <h1 className='md:text-[30px] text-[18px] medium mt-[24px] mb-[16px] text-[#141414] md:font-[500] md:leading-[38px] md:pb-[50px] medium ' >Attendance 01</h1>

                    <div className='w-full h-[78vh] bg-white overflow-scroll scroll-hidden'>
                            <table>
                                <thead>
                                    <tr>
                                        <td className='text-[14px] md:text-[16px]'>#</td>
                                        <td className='text-[14px] md:text-[16px]'>Full Name</td>
                                        <td className='text-[14px] md:text-[16px]'>Matriculation No.</td>
                                    </tr>
                                </thead>

                                <tbody>
                                    {Courses[1]?.students?.map((student, index) => (
                                        <tr key={index}>                                        
                                            <td className='text-[14px] md:text-[16px]'>{student.sn} </td>
                                            <td className='text-[14px] md:text-[16px]'>{student.name}</td>
                                            <td className='text-[14px] md:text-[16px]'>{student.matno}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                </DashboardLayout>
            </main>
        </div>
    )
}

export default SingleAttendance