import Head from 'next/head'
import React, { useState, useRef, useEffect } from 'react'
import StudentHeader from '../../components/StudentHeader'
import Image from 'next/image'
// import QrReader from 'react-qr-scanner'
import AttendanceGrid from '../../components/AttendanceGrid'
import Scan from '../../components/Scan'
import { QrReader } from 'react-qr-reader';
import axios from 'axios'

const Index = () => {
    const [user, setUser] = useState()
    const [courses, setCourses] = useState()
    const [scan, setScan] = useState(false);
    const [attendance, setAttendance] = useState([])
    const [Session, setSession] = useState([])
    const [course, setCourse] = useState([])
    const [called, setCalled] = useState(false)
    const qrRef = useRef(null)
    const sessionArray = []
    const userArray = []

    // useEffect(() => {
    //     const user = JSON.parse(window.localStorage.getItem("user"))
    //     if (user) {
    //         setUser(user)
    //     }
    // }, [])

    // useEffect(() => {
    //     if (user) {
    //         setCourses(user.courses)
    //     }
    // }, [user])

    // useEffect(() => {
    //     if (courses) {
    //         courses?.forEach(element => {
    //             getSession(element.id)
    //         });

    //     }


    // }, [courses])

    // useEffect(() => {
    //     console.log("calllld")
    //     if (!called) {
    //         console.log(course)
    //     }


    // }, [called])


    // const getSession = async (id) => {
    //     await axios.get(`https://attendx-2hi6.onrender.com/session/get-session/${id}`).then((res) => {
    //         console.log(res)


    //         res.data.forEach((data) => {
    //             sessionArray.push({ course_code: data.course_code })
    //             console.log(res)
    //             // Session.push(data)
    //             if (!course.includes({ "course_code": data.course_code, "percentage": 0 })) {
    //                 course.push({ "course_code": data.course_code, "percentage": 0 })
    //             }
    //             data.attendance.forEach((attend) => {
    //                 if (attend.matric_number === user.identity_number) {
    //                     userArray.push({"course_code":data.course_code})

    //                 }
    //             })
    //         })

    //         sessionArray.length > 0 && setSession(sessionArray)
    //         userArray.length > 0 && setAttendance(userArray)


    //         console.log({ "Session": sessionArray, "user": userArray })

    //     })



    // }


    return (
        <div className='w-full'>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=" bg-[#F4F4F4] h-full">

                {scan ? <Scan />
                    :
                    <>

                        <StudentHeader />
                        <div className='md:px-[128px] mt-[40px] px-[20px] h-full  pb-[400px]'>
                            <div className='flex items-center justify-between mb-[32px]'>
                                <h1 className='text-[18px] md:text-[30px] medium text-[#141414]'>Class Attendance</h1>
                                <div className='bg-[#183DA7] rounded-md py-[8px] px-[16px] md:flex space-x-[8px] cursor-pointer hidden' onClick={() => {
                                    setScan(true)
                                }}>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M10 22C6.22876 22 4.34315 22 3.17157 20.8284C2 19.6569 2 18.7712 2 15" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M22 15C22 18.7712 22 19.6569 20.8284 20.8284C19.6569 22 17.7712 22 14 22" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M14 2C17.7712 2 19.6569 2 20.8284 3.17157C22 4.34315 22 5.22876 22 9" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M10 2C6.22876 2 4.34315 2 3.17157 3.17157C2 4.34315 2 5.22876 2 9" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M2 12H22" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                    </svg>
                                    <h2 className='text-white'>Scan Code</h2>
                                </div>
                                <div className='fixed right-[20px] items-center justify-center flex bottom-[20%] bg-[#183DA7] rounded-full w-[48px] h-[48px] md:hidden' onClick={() => {
                                    setScan(true)
                                }}>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M10 22C6.22876 22 4.34315 22 3.17157 20.8284C2 19.6569 2 18.7712 2 15" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M22 15C22 18.7712 22 19.6569 20.8284 20.8284C19.6569 22 17.7712 22 14 22" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M14 2C17.7712 2 19.6569 2 20.8284 3.17157C22 4.34315 22 5.22876 22 9" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M10 2C6.22876 2 4.34315 2 3.17157 3.17157C2 4.34315 2 5.22876 2 9" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M2 12H22" stroke="white" stroke-width="1.5" stroke-linecap="round" />
                                    </svg>
                                </div>




                            </div>
                            <AttendanceGrid />
                        </div>


                    </>
                }
            </main>

        </div>
    )
}

export default Index