import Head from 'next/head'
import React, { useState, useRef, useEffect } from 'react'
import StudentHeader from '../../components/StudentHeader'
import Image from 'next/image'
// import QrReader from 'react-qr-scanner'
import AttendanceGrid from '../../components/AttendanceGrid'
import Scan from '../../components/Scan'
import { QrReader } from 'react-qr-reader';
import axios from 'axios'

const Index = () => {
    const [user, setUser] = useState()
    const [courses, setCourses] = useState()
    const [scan, setScan] = useState(false);
    const [attendance, setAttendance] = useState([])
    const [Session, setSession] = useState([])
    const [called, setCalled] = useState(false)
    const qrRef = useRef(null)


    useEffect(() => {
        const user = JSON.parse(window.localStorage.getItem("user"))
        if (user) {
            console.log(user)
            setUser(user)
        }
    }, [])

    useEffect(() => {
        if (user) {
            setCourses(user.courses)
        }
    }, [user])

    useEffect(() => {
        if (courses) {
            console.log(courses)
            courses?.forEach(element => {
                getSession(element.id)
            });
        }
    }, [courses])

    useEffect(() => {
        console.log("calllld")
        if (!called) {
            console.log(attendance)
        }

    }, [called])

    const getSession = async (id) => {
        await axios.get(`https://attendx-2hi6.onrender.com/session/get-session/${id}`).then((res) => {
            console.log(res)
            res.data.forEach((data) => {
                Session.push(data)
                // console.log(Session)
                data.attendance.forEach((attend) => {
                    if (attend.matric_number === user.identity_number) {
                        if (!attendance.includes(data)) {
                            attendance.push(data)
                        }
                        setCalled(!called)
                        console.log("heyyy")
                        console.log(attendance)
                    }
                })
            })
        })
    }


    return (
        <div className='w-full'>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=" bg-[#F4F4F4] h-full">

                {scan ? <Scan />
                    :
                    <>

                        <StudentHeader />
                        <div className='md:px-[128px] mt-[40px] px-[20px] h-screen'>
                            <div className='flex items-center justify-between mb-[32px]'>
                                <h1 className='text-[18px] md:text-[30px] medium text-[#141414]'>Class Attendance</h1>
                                <div className='bg-[#183DA7] rounded-md py-[8px] px-[16px] md:flex space-x-[8px] cursor-pointer hidden' onClick={() => {
                                    setScan(true)
                                    // onScanFile()
                                }}>
                                    <Image src="/image/Frame.svg" width={20} height={20} alt="scan" />
                                    <h2 className='text-white'>Scan Code</h2>
                                </div>
                                <div className='fixed right-[20px] items-center justify-center flex bottom-[20%] bg-[#183DA7] rounded-full w-[48px] h-[48px] md:hidden' onClick={() => {
                                    setScan(true)
                                    // onScanFile()

                                }}>
                                    <Image src="/image/Frame.svg" width={20} height={20} alt="scan" />
                                </div>




                            </div>
                            {attendance.length > 0 && (<AttendanceGrid session={Session} attendance={attendance} />)}
                        </div></>
                }
            </main>

        </div>
    )
}

export default Index