import Head from 'next/head'
import React, { useState } from 'react'
import DashboardLayout from '../../components/DashboardLayout'
import Button from '../../components/Button';
import CourseModal from '../../components/CourseModal';

const AddCourse = () => {

    const [open, setOpen] = useState(false)

    const Attendance = [
        {
            serialNumber: 1,
            courseCode: 'CS101',
            courseTitle: 'Introduction to Computer Science',
            credit: "3 Credit",
            semester: "1st Sem."

        },
        {
            serialNumber: 2,
            courseCode: 'ENG202',
            courseTitle: 'Advanced English Composition',
            credit: "4 Credit",
            semester: "1st Sem."
        },
        {
            serialNumber: 3,
            courseCode: 'MAT150',
            courseTitle: 'Calculus I',
            credit: "5 Credit",
            semester: "1st Sem."
        },
        {
            serialNumber: 4,
            courseCode: 'PHY110',
            courseTitle: 'Physics for Engineers',
            credit: "4 Credit",
            semester: "1st Sem."
        },
        {
            serialNumber: 5,
            courseCode: 'HIS220',
            courseTitle: 'World History: 20th Century',
            credit: "3 Credit",
            semester: "1st Sem."
        },
        {
            serialNumber: 6,
            courseCode: 'BIO101',
            courseTitle: 'Introduction to Biology',
            credit: "4 Credit",
            semester: "1st Sem."
        },
        // {
        //     serialNumber: 7,
        //     courseCode: 'CHEM120',
        //     courseTitle: 'General Chemistry',
        //     credit: "5 Credit" ,
        //     semester: "1st Sem."
        // },
        // {
        //     serialNumber: 8,
        //     courseCode: 'PSY201',
        //     courseTitle: 'Introduction to Psychology',
        //     credit: "3 Credit" ,
        //     semester: "1st Sem."
        // },
        // {
        //     serialNumber: 9,
        //     courseCode: 'ART110',
        //     courseTitle: 'Introduction to Art and Design',
        //     credit: "3 Credit" ,
        //     semester: "1st Sem."
        // },
        // {
        //     serialNumber: 10,
        //     courseCode: 'ECON301',
        //     courseTitle: 'Microeconomics',
        //     credit: "4 Credit" ,
        //     semester: "1st Sem."
        // }
    ];



    return (
        <div>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>


                {open ? <CourseModal text="update" texting="updating" setOpen={setOpen} color="bg-[#183DA7]" icon="image/Notebook.svg" /> :

                    <DashboardLayout>

                        <div className='pb-[16px] md:pb-[32px] flex justify-between items-center'>
                            <h1 className='text-[#141414] font-[500] text-[18px]  md:text-[30px] leading-[28px]  md:leading-[38px] medium  '> Add new course </h1>
                        </div>


                        <>
                            <div className='w-full h-[65vh] bg-transparent  md:bg-white overflow-scroll scroll-hidden overflow-x-scroll scroll-hidden'>
                                <table className='w-[900px] bg-transparent'>
                                    <thead className='bg-gray-200 md:bg-white w-full'>
                                        <tr>
                                            <td className='text-[14px] md:text-[16px]'><input type='checkbox' disabled /></td>
                                            <td className='text-[14px] md:text-[16px]'>Semester</td>
                                            <td className='text-[14px] md:text-[16px]'>Course Code</td>
                                            <td className='text-[14px] md:text-[16px]'>Course Title</td>
                                            <td className='text-[14px] md:text-[16px]'>Credit</td>

                                        </tr>
                                    </thead>


                                    <tbody >
                                        {Attendance.map((Attendance, index) => (
                                            <tr key={index} className=''>
                                                <td className='text-[14px] md:text-[16px]'><input type='checkbox' /></td>
                                                <td className='text-[14px] md:text-[16px]'>{Attendance.semester}</td>
                                                <td className='text-[14px] md:text-[16px]'>{Attendance.courseCode}</td>
                                                <td className='text-[14px] md:text-[16px]'>{Attendance.courseTitle}</td>
                                                <td className='text-[14px] md:text-[16px]'>{Attendance.credit}</td>

                                            </tr>
                                        ))}
                                    </tbody>


                                </table>


                            </div>


                            <div className='w-[150px] mt-[32px]' onClick={() => {
                                setOpen(true)
                            }}>
                                <Button text="Update Course" />
                            </div>
                        </>

                    </DashboardLayout>
                }
            </main>
        </div>
    )
}

export default AddCourse