import Head from 'next/head'
import Image from 'next/image'
import DashboardLayout from '../../components/DashboardLayout'
import DashboardBtn from '../../components/DashboardBtn'
import { useEffect, useRef, useState } from 'react'
import { Courses } from "../../data"
import StudentCourse from '../../components/StudentCourse'
import StudentNoCourse from '../../components/StudentNoCourse'
import axios from 'axios'


export default function Home() {
    const [staffID, setStaffID] = useState("")
    const [courses, setCourses] = useState([])
    const [selectedCourse, setSelectedCourse] = useState([])


    useEffect(() => {
        const user = JSON.parse(window.localStorage.getItem("user"))
        console.log(user)
        if (user) {
            setCourses(user.courses)
        }
    }, [])

    useEffect(() => {
        console.log("Courses")
        console.log(courses)
        if (courses) {
            setSelectedCourse(courses[0])
        }
    }, [courses])






    return (
        <div>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="w-full h-screen">
                <DashboardLayout>
                    {courses?.length >=1 ? <StudentCourse /> : <StudentNoCourse />}
                </DashboardLayout>
            </main>

        </div>
    )
}

