import Head from 'next/head'
import Image from 'next/image'
import DashboardLayout from '../../components/DashboardLayout'
import DashboardBtn from '../../components/DashboardBtn'
import { useEffect, useRef, useState } from 'react'
import { Courses } from "../../data"
import StudentCourse from '../../components/StudentCourse'
import StudentNoCourse from '../../components/StudentNoCourse'


export default function Home() {
    
    console.log(Courses)
   


    return (
        <div>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="w-full h-screen">
                <DashboardLayout>
                    {Courses.length > 1 ? <StudentCourse /> :  <StudentNoCourse /> }
                </DashboardLayout>
            </main>

        </div>
    )
}

