import Head from 'next/head'
import Image from 'next/image'
import SignupHeader from '../components/SignupHeader'
import SignUpMain from '../components/SignupMain'
import Signin from '../components/Signin'



export default function Home() {
    return (
        <div className='w-full'> 
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-[#FFFFFF] md:px-[64px] px-[16px] flex flex-col items-center h-screen md:h-full justify-center ">

                <SignupHeader login="true" />

                <div className=" md:w-[490px] w-full md:mx-auto md:mt-[60px] md:mb-[100px]">
                    <Signin />
                </div>
            </main>

        </div>
    )
}

