import Head from 'next/head'
import Image from 'next/image'
import Signin from '../components/Signin'
import SignupHeader from '../components/SignupHeader'
import SignUpMain from '../components/SignupMain'


export default function Home() {
    return (
        <div>
            <Head>
                <title>Attend X</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-[#FFFFFF] px-[16px] md:px-[64px] h-screen md:h-full flex justify-center items-center flex-col">

                <SignupHeader login="true" />

                <div className="w-full md:w-[490px] mx-auto mb-[100px]">
                    <div className="md:mt-[60px] md:w-[450px] mx-auto">
                        <Signin />
                    </div>
                </div>
            </main>

        </div>
    )
}

